name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/shared-steps.yml
      - name: Test
        run: dotnet test --no-build --verbosity normal
